#!/usr/bin/env python

from presence.bot    import PresenceBot

import logging

def main():
    logger = logging.getLogger('presence-minimal')
    logFormatter = logging.Formatter("%(asctime)s [%(levelname)-5.5s] [%(threadName)s] %(message)s")

    # logging to console
    consoleHandler = logging.StreamHandler()
    consoleHandler.setFormatter(logFormatter)
    logger.addHandler(consoleHandler)
    
    logger.setLevel( logging.DEBUG)
    
    p = PresenceBot(logger=logger)
    p.listen()
    
    try:
        while True:
            p.wait_for_connect()
    except KeyboardInterrupt:
        logger.info("Interrupted by user")
    
    p.cleanup()

if __name__ == '__main__':
    main()
