#!/usr/bin/env python

from presence.presence import Presence
from presence.bot      import PresenceBot

def main():
    p = PresenceBot()
    p.listen()
    
    try:
        while True:
            p.wait_for_connect()
    except KeyboardInterrupt:
        print "KeyboardInterrupt"
    
    p.cleanup()

if __name__ == '__main__':
    main()
